# Generated by Django 4.1.2 on 2022-11-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tags_product_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
