# Generated by Django 4.1.2 on 2022-11-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
