# Generated by Django 4.1.2 on 2022-11-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_product_categories_remove_product_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('all', 'all'), ('mobile', 'mobile'), ('laptop', 'laptop'), ('watch', 'watch'), ('accessory', 'accessory')], default='all', max_length=70),
        ),
        migrations.AddField(
            model_name='product',
            name='product_avail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_catogory',
            field=models.CharField(choices=[('all', 'all'), ('mobile', 'mobile'), ('earphones', 'earphones'), ('keyboard', 'keyboard'), ('mouse', 'mouse'), ('headset', 'headset'), ('laptop', 'laptop'), ('pc', 'pc'), ('mobile-case', 'mobile-case'), ('laptop-case', 'laptop-case'), ('ladies-watch', 'ladies-watch'), ('mens-watch', 'mens-watch'), ('camera', 'camera'), ('mobile-accessory', 'mobile-accessory'), ('speaker', 'speaker'), ('laptop-accessory', 'laptop-accessory')], default='all', max_length=70),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images'),
        ),
    ]
