# Generated by Django 4.1.2 on 2022-11-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_category_product_product_avail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sponsered',
            field=models.BooleanField(default=False),
        ),
    ]
