# Generated by Django 4.1.3 on 2022-11-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_orderitem_remove_item_cart_remove_item_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_catogory',
            field=models.CharField(choices=[('all', 'all'), ('mobile', 'mobile'), ('earphone', 'earphone'), ('keyboard', 'keyboard'), ('mouse', 'mouse'), ('headset', 'headset'), ('laptop', 'laptop'), ('pc', 'pc'), ('mobile-case', 'mobile-case'), ('laptop-case', 'laptop-case'), ('ladies-watch', 'ladies-watch'), ('mens-watch', 'mens-watch'), ('camera', 'camera'), ('mobile-accessory', 'mobile-accessory'), ('speaker', 'speaker'), ('laptop-accessory', 'laptop-accessory')], default='all', max_length=70),
        ),
    ]
