# Generated by Django 4.1.2 on 2022-11-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_product_product_catogory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='isadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='ismoderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='isnormaluser',
            field=models.BooleanField(default=True),
        ),
    ]
